"""Record an actual, checkpoint-verified three-minute demo with English subtitles."""
import argparse
import json
from pathlib import Path
import sys
import time
from playwright.sync_api import sync_playwright
sys.path.insert(0,str(Path(__file__).resolve().parent.parent))
from odin.reporting import validate_report
from render_demo import render


def timestamp(seconds):
    ms=round(seconds*1000)
    return f'{ms//3600000:02}:{ms//60000%60:02}:{ms//1000%60:02},{ms%1000:03}'


if __name__=='__main__':
    p=argparse.ArgumentParser()
    p.add_argument('--url',default='http://127.0.0.1:8766')
    p.add_argument('--report',default='results/official.json')
    p.add_argument('--output',default='submission/video')
    p.add_argument('--chromium',help='Optional Chromium executable; otherwise uses Playwright installation')
    a=p.parse_args()
    out=Path(a.output).resolve();out.mkdir(parents=True,exist_ok=True)
    report=json.loads(Path(a.report).read_text())
    validate_report(report,report.get('checkpoint_sha256'))
    captions=[]
    with sync_playwright() as pw:
        browser=pw.chromium.launch(headless=True,**({'executable_path':a.chromium} if a.chromium else {}))
        context=browser.new_context(viewport={'width':1440,'height':1000},record_video_dir=str(out/'raw'),record_video_size={'width':1440,'height':1000})
        page=context.new_page()
        start=time.monotonic()
        page.goto(a.url)
        status=page.request.get(a.url+'/api/status').json()
        if not status['ready'] or status['checkpoint_sha256']!=report['checkpoint_sha256']:
            raise ValueError('The browser must load the exact fully evaluated checkpoint')
        validate_report(report,status['checkpoint_sha256'])
        m=status['model']
        def caption(text,duration):
            now=time.monotonic()-start
            captions.append((now,now+duration,text))
            page.wait_for_timeout(duration*1000)
        caption('ODIN Pocket: a language model built from its first weight.\nGIBC V2 — Track 01: Foundational LLM Development.',12)
        caption(f"{m['parameter_count']:,} trainable parameters, including embeddings and output.\nThe whole model fits below the 50 million parameter limit.",12)
        page.locator('#prompt').fill('The ocean stores heat from the sun. As the surface water warms,')
        page.locator('#generate').click()
        page.wait_for_function("() => !document.getElementById('generate').disabled",timeout=180000)
        if 'tokens/s' not in page.locator('#generation-stats').inner_text():
            raise RuntimeError('Generation failed; do not record a fabricated demonstration')
        caption(f"This continuation is generated by our local checkpoint on {status['inference_device'].upper()}.\nThere is no inference API, retrieval substitute, or scripted answer.",14)
        caption('It is a base language model: give it a beginning, not an instruction.\nIts generated text can be repetitive or factually wrong.',12)
        page.locator('#tokenize').scroll_into_view_if_needed()
        if page.locator('#tokens button').count():
            page.locator('#tokens button').first.click()
        caption('The tokens below come from that exact generation.\nSelect one to inspect the probability before sampling.',12)
        page.locator('[data-view=compare]').click()
        page.locator('#compare').click()
        page.wait_for_function("() => !document.getElementById('compare').disabled",timeout=180000)
        if page.locator('.candidate-result').count()!=2:
            raise RuntimeError('Comparison failed')
        caption('The second tool compares possible endings using causal log likelihood.\nBoth candidates are scored by the same model.',14)
        caption('We normalize by candidate token count. Higher means more likely,\nnot more truthful: this preference is not a fact check.',12)
        page.locator('[data-view=evidence]').click()
        page.wait_for_function("() => document.querySelectorAll('#benchmarks tr').length === 5")
        expected=[f"{report['results'][name]['acc,none']*100:.2f}%" for name in ('hellaswag','arc_easy','piqa','winogrande')]
        expected.append(f"{report['wikitext_103']['token_perplexity']:.2f} token PPL")
        for index,value in enumerate(expected):
            cells=page.locator('#benchmarks tr').nth(index).locator('td').all_text_contents()
            if cells[2:]!=[value,'Full split']:
                raise ValueError('Rendered benchmark differs from the verified report: '+str(cells))
        page.evaluate('window.scrollTo(0,0)')
        caption(f"Training hardware: {m['provenance']['hardware']}.\n{m['tokens']:,} tokens processed in {m['training_seconds']/3600:.2f} recorded hours.",14)
        caption('The development loss curve comes directly from the training log.\nThe page shows only evidence tied to the loaded training run.',12)
        page.locator('#benchmarks').scroll_into_view_if_needed()
        caption('These are full, zero-shot evaluations through lm-evaluation-harness:\nHellaSwag, ARC-Easy, PIQA and WinoGrande.',14)
        caption('WikiText-103 measures held-out language modeling.\nToken perplexity depends on the tokenizer; the full protocol is documented.',12)
        page.locator('.provenance summary').click()
        page.locator('.provenance').scroll_into_view_if_needed()
        caption('Weights start randomly. Training uses public FineWeb-Edu and WikiText text.\nNo pretrained weights, private teacher targets, or distillation.',12)
        caption('Checkpoint identity, source code, training recipe and measured results\nmake the experiment reproducible. Development was assisted by OpenAI Codex.',12)
        video=page.video
        context.close()
        raw=Path(video.path())
        browser.close()
    srt=out/'demo.en.srt'
    srt.write_text('\n\n'.join(f'{i+1}\n{timestamp(begin)} --> {timestamp(end)}\n{text}' for i,(begin,end,text) in enumerate(captions))+'\n')
    target=out/'odin-pocket-demo.mp4'
    render(raw,srt,target)
    print(json.dumps({'video':str(target),'subtitles':str(srt),'checkpoint_sha256':status['checkpoint_sha256'],'caption_end_seconds':captions[-1][1]}),flush=True)
