'use strict';
const $=id=>document.getElementById(id);
const examples={science:'The ocean stores heat from the sun. As the surface water warms,',story:'The lighthouse keeper found a small wooden box on the beach. Inside the box was',everyday:'Plants need sunlight to grow because'};
let currentStatus=null;
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(180000)});const result=await response.json();if(!response.ok)throw new Error(result.error||'The local server could not complete the request.');return result;}
function format(n){return Number.isFinite(n)?new Intl.NumberFormat('en',{maximumFractionDigits:0}).format(n):'Unmeasured';}
async function action(button,working,fn){const original=button.textContent;button.disabled=true;button.textContent=working;notice('');try{await fn();}catch(e){notice(e.name==='TimeoutError'?'The local model took too long. Try a shorter continuation.':e.message);}finally{button.disabled=false;button.textContent=original;}}
async function status(){try{const s=await api('/api/status');currentStatus=s;$('connection').textContent=s.ready?'● Checkpoint loaded · '+s.inference_device.toUpperCase():'○ Waiting for a checkpoint';$('model-badge').textContent=s.ready?`ODIN / ${(s.model.parameter_count/1e6).toFixed(1)}M`:'ODIN / POCKET';$('model-caption').textContent=s.ready?`${format(s.model.parameter_count)} parameters · ${format(s.model.tokens)} training tokens`:'From-scratch causal language model';if(!s.ready)notice(s.message);}catch(e){$('connection').textContent='○ Server unavailable';notice('Start the local server, then reload this page.');}}
function show(view){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view+'-view');document.querySelectorAll('.nav').forEach(el=>{const active=el.dataset.view===view;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});if(view==='evidence')evidence().catch(e=>notice(e.message));}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{location.hash=b.dataset.view;show(b.dataset.view);}));
window.addEventListener('hashchange',()=>show(['write','compare','evidence'].includes(location.hash.slice(1))?location.hash.slice(1):'write'));
document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{$('prompt').value=examples[b.dataset.example];$('completion').textContent='';$('prompt').focus();}));
for(const id of ['length','temperature'])$(id).addEventListener('input',()=>$(id+'-value').textContent=$(id).value);
function renderTokens(tokens,probabilities){$('tokens').replaceChildren();for(const token of tokens){const el=document.createElement('button');el.type='button';el.className='token'+(probabilities&&token.probability<.05?' low':'');el.textContent=token.text.replaceAll('\n','↵');el.title=`Token ${token.id}`+(probabilities?` · probability ${(token.probability*100).toFixed(2)}%`:'');el.setAttribute('aria-label',el.title);el.addEventListener('click',()=>{$('token-caption').textContent=el.title+' · '+JSON.stringify(token.text);});$('tokens').append(el);}}
$('generate').addEventListener('click',()=>action($('generate'),'Generating locally…',async()=>{const result=await api('/api/generate',{prompt:$('prompt').value,max_new_tokens:Number($('length').value),temperature:Number($('temperature').value)});$('completion').textContent=result.text||'The model ended the passage immediately. Try another beginning or more variation.';$('generation-stats').textContent=`${result.tokens} tokens · ${result.seconds.toFixed(2)}s · ${result.tokens_per_second.toFixed(1)} tokens/s`;renderTokens(result.trace,true);$('token-caption').textContent='Actual generated tokens. Hover to see the raw model probability before sampling. Pale tokens had less than 5% probability.';if(result.context_truncated)notice('The beginning exceeded the model context. Only the most recent context tokens were used.');}));
$('tokenize').addEventListener('click',()=>action($('tokenize'),'Inspecting…',async()=>{const result=await api('/api/tokenize',{prompt:$('prompt').value});renderTokens(result.tokens,false);$('token-caption').textContent=`Your beginning contains ${format(result.count)} tokens. Showing the first ${Math.min(result.count,result.display_limit)}; some Unicode characters span multiple tokens.`;}));
$('compare').addEventListener('click',()=>action($('compare'),'Comparing locally…',async()=>{const result=await api('/api/compare',{prompt:$('compare-prompt').value,candidates:[$('candidate-a').value,$('candidate-b').value]});$('comparison-results').replaceChildren();result.candidates.forEach((candidate,i)=>{const row=document.createElement('section');row.className='candidate-result'+(i===result.preferred?' preferred':'');const h=document.createElement('h3');h.textContent=`Ending ${String.fromCharCode(65+i)}${i===result.preferred?' · Model preference':''}`;const p=document.createElement('p');p.textContent=candidate.text;const small=document.createElement('small');small.textContent=`${candidate.mean_log_likelihood.toFixed(3)} mean log likelihood · ${candidate.tokens} tokens · higher is more likely`;row.append(h,p,small);$('comparison-results').append(row);});}));
$('reload').addEventListener('click',()=>action($('reload'),'Loading…',async()=>{await api('/api/reload',{});clearOutputs();await status();if(location.hash==='#evidence')await evidence();}));
function clearOutputs(){$('completion').textContent='Your continuation will appear here.';$('comparison-results').replaceChildren();$('generation-stats').textContent='Every continuation is generated locally.';$('tokens').replaceChildren();$('token-caption').textContent='Generate a passage or inspect input tokens.';chart([]);}
function chart(rows){const empty=document.createElement('p');empty.className='muted';empty.textContent='No matching training measurements for this checkpoint.';$('loss-chart').replaceChildren(empty);const valid=rows.filter(r=>Number.isFinite(r.dev_loss));if(!valid.length)return;const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 560 200');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Development loss from ${valid[0].dev_loss.toFixed(2)} to ${valid.at(-1).dev_loss.toFixed(2)}`);const min=Math.floor(Math.min(...valid.map(r=>r.dev_loss))),max=Math.ceil(Math.max(...valid.map(r=>r.dev_loss)));const last=Math.max(1,valid.at(-1).tokens);const x=r=>45+r.tokens/last*495,y=v=>160-(v-min)/Math.max(1,max-min)*140;for(let i=0;i<4;i++){const value=min+(max-min)*i/3;const line=document.createElementNS(ns,'line');line.setAttribute('x1','40');line.setAttribute('x2','545');line.setAttribute('y1',y(value));line.setAttribute('y2',y(value));line.setAttribute('class','chart-axis');svg.append(line);const text=document.createElementNS(ns,'text');text.setAttribute('x','4');text.setAttribute('y',y(value)+4);text.setAttribute('class','chart-label');text.textContent=value.toFixed(1);svg.append(text);}const path=document.createElementNS(ns,'path');path.setAttribute('d',valid.map((r,i)=>`${i?'L':'M'}${x(r)},${y(r.dev_loss)}`).join(' '));path.setAttribute('class','chart-line');svg.append(path);for(const [px,label] of [[45,'0 tokens'],[420,`${(last/1e6).toFixed(1)}M tokens`]]){const text=document.createElementNS(ns,'text');text.setAttribute('x',px);text.setAttribute('y','188');text.setAttribute('class','chart-label');text.textContent=label;svg.append(text);}$('loss-chart').replaceChildren(svg);}
async function evidence(){await status();const s=currentStatus;if(!s)return;const m=s.model;$('parameters').textContent=format(m.parameter_count);$('training-tokens').textContent=format(m.tokens);$('training-time').textContent=m.training_seconds?`${(m.training_seconds/3600).toFixed(2)} hours recorded`:'No training record loaded';$('hardware').textContent=m.provenance?.hardware||'Unmeasured';$('inference-device').textContent=(s.inference_device||'cpu').toUpperCase()+' · local';$('layers').textContent=m.config?`${m.config.layers} / ${m.config.width}`:'Unmeasured';$('heads').textContent=m.config?`Rotary positions · ${m.config.heads} heads`:'Unmeasured';$('vocab').textContent=m.config?`${format(m.config.vocab_size)}-entry byte BPE`:'Unmeasured';$('provenance').textContent=JSON.stringify({checkpoint_sha256:s.checkpoint_sha256,...m},null,2);const result=await api('/api/evidence');chart(result.training);const rows=[['hellaswag','HellaSwag','Plausible event completion'],['arc_easy','ARC-Easy','Elementary science'],['piqa','PIQA','Physical commonsense'],['winogrande','WinoGrande','Pronoun resolution'],['wikitext_103','WikiText-103','Held-out language modeling']];$('benchmarks').replaceChildren();let count=0;for(const [key,label,meaning] of rows){const report=[...result.reports].sort((a,b)=>(Number(b.status==='full')-Number(a.status==='full'))||String(b.created_at||'').localeCompare(String(a.created_at||''))).find(r=>key==='wikitext_103'?r.wikitext_103:r.results?.[key]);let value='Not yet measured',coverage='—';if(report){count++;const metrics=report.results?.[key];value=key==='wikitext_103'?report.wikitext_103.token_perplexity.toFixed(2)+' token PPL':((metrics['acc,none']??metrics.acc)*100).toFixed(2)+'%';coverage=report.status==='full'?'Full split':`Partial · limit ${report.limit}`;}const tr=document.createElement('tr');for(const text of [label,meaning,value,coverage]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('benchmarks').append(tr);}$('benchmark-status').textContent=`${count} / 5 measured for this checkpoint`;}
status().then(()=>show(['write','compare','evidence'].includes(location.hash.slice(1))?location.hash.slice(1):'write'));
